<?php

return array (
  'APP_SECRET' => NULL,
  'DATABASE_PASSWORD' => NULL,
  'JWT_PASSPHRASE' => NULL,
  'MAILER_DSN' => NULL,
  'MERCURE_JWT_TOKEN' => NULL,
  'MERCURE_SECRET_KEY' => NULL,
  'TELEGRAM_BOT_TOKEN' => NULL,
  'TELEGRAM_CHAT_ID' => NULL,
);
