services:
  # default configuration for services in *this* file
  _defaults:
    public: false
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Monolog\Processor\MemoryUsageProcessor: ~

  Monolog\Processor\MemoryPeakUsageProcessor: ~

  Monolog\Processor\ProcessIdProcessor: ~

  Monolog\Processor\IntrospectionProcessor: ~

  Symfony\Bridge\Monolog\Processor\WebProcessor: ~

  Symfony\Bridge\Monolog\Processor\RouteProcessor:
    tags:
      - {name: monolog.processor }

  Symfony\Bridge\Monolog\Processor\DebugProcessor:
    tags:
      - {name: monolog.processor }

  LaSalle\GroupZero\Logging\Infrastructure\Monolog\Formatter\JsonPrettyFormatter: ~

  jacklul\MonologTelegramHandler\TelegramHandler:
    arguments:
      $token: '%env(resolve:TELEGRAM_BOT_TOKEN)%'
      $chatId: '%env(resolve:TELEGRAM_CHAT_ID)%'
      $level: !php/const Monolog\Logger::EMERGENCY

  # Actually is not needed due autowiring loads automatically the Processor
  LaSalle\GroupZero\Logging\Infrastructure\Monolog\Processor\IdProcessor:
    tags:
      - { name: monolog.processor }

  LaSalle\GroupZero\Logging\Infrastructure\Monolog\Processor\FakeWebProcessor:
    autoconfigure: false

  Monolog\Processor\PsrLogMessageProcessor: ~
