LaSalle\GroupZero\Logging\Domain\Model\Aggregate\LogSummary:
  type: entity
  table: log_summary
  uniqueConstraints:
    environmentLevel:
      columns: [environment, level]
  id:
    id:
      type: log_summary_id
  embedded:
    count:
      class: LaSalle\GroupZero\Logging\Domain\Model\ValueObject\LogCount
      columnPrefix: false
  fields:
    level:
      type: log_level
    environment:
      type: environment
    updatedOn:
      type: datetime_immutable

