doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                    enum: string
        types:
            log_level:  LaSalle\GroupZero\Logging\Infrastructure\Persistence\Doctrine\Type\LogLevelType
            environment:  LaSalle\GroupZero\Logging\Infrastructure\Persistence\Doctrine\Type\EnvironmentType
            log_summary_id:  LaSalle\GroupZero\Logging\Infrastructure\Persistence\Doctrine\Type\LogSummaryIdType
            log_count:  LaSalle\GroupZero\Logging\Infrastructure\Persistence\Doctrine\Type\LogCountType
            user_id:  LaSalle\GroupZero\User\Infrastructure\Persistence\Doctrine\Type\UserIdType
            user_role_collection:  LaSalle\GroupZero\User\Infrastructure\Persistence\Doctrine\Type\UserRoleCollectionType
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    LaSalleGroupZeroLoggingDomainModel:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/src/Logging/Infrastructure/Persistence/Doctrine/Resources/mapping'
                        prefix: LaSalle\GroupZero\Logging\Domain\Model
                    LaSalleGroupZeroUserDomainModel:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Resources/mapping'
                        prefix: LaSalle\GroupZero\User
