doctrine_migrations:
    dir_name: '%kernel.project_dir%/migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
    table_name: migration_versions
    name: Application Migrations
    column_name: 'version'
    column_length: 18
