# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    format_listener:
      enabled: true
      rules:
        - { path: ^/api/, prefer_extension: false, fallback_format: ~, priorities: [ json ] }
        - { path: ^/sandbox, stop: true }
        - { path: ^/, stop: true }
    routing_loader:
      default_format: json
    view:
        view_response_listener:
          enabled: true
          force: false
        mime_types:
          json: ['application/json;version=2.0']
    versioning:
      enabled: true
      resolvers:
        media_type:
          enabled: true
          regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    service:
        serializer:

    exception:
        enabled: true
        codes:
            LaSalle\GroupZero\Logging\Domain\Model\Exception\InvalidLogLevelException: 400
        messages:
            LaSalle\GroupZero\Logging\Domain\Model\Exception\InvalidLogLevelException: true
