jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: true
        directories:
            logging_context:
                namespace_prefix: "LaSalle\\GroupZero\\Logging"
                path: "%kernel.project_dir%/src/Logging/Infrastructure/Framework/Resources/config/serializer"
