version: '3.5'

services:
  nginx:
    image: fnandot/nginx:1.11-mpwar
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
        read_only: true

  php-fpm:
    image: fnandot/php-fpm:8.0.3-mpwar
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
        read_only: false
    env_file:
      - docker.env
