version: '3.5'

services:
  nginx:
    image: mpwar2021/nginx:1.19-alpine
    build: docker/nginx
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
        read_only: true

  php-fpm:
    image: mpwar2021/php-fpm:8.0.3
    build: docker/php-fpm
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
        read_only: false
    env_file:
      - docker.env
