version: '3.5'

services:
  kibana:
    image: kibana:5.5
    ports:
      - 5601:5601
    volumes:
      - type: bind
        source: $PWD/docker/kibana/config
        target: /usr/share/kibana/config
        read_only: true

  elasticsearch:
    image: elasticsearch:5.5
    ports:
      - 9200:9200

volumes:
  db_data:
