LaSalle\GroupZero\Logging\Domain\Model\Aggregate\LogEntry:
  attributes:
    id:
      groups: [api-v1]
    environment:
      groups: [api-v1]
    level:
      groups: [api-v1]
    message:
      groups: [api-v1]
    occurredOn:
      groups: [api-v1]
