LaSalle\GroupZero\Logging\Application\LogEntryResponse:
  attributes:
    id:
      groups: [api-v1]
    environment:
      groups: [api-v1]
    level:
      groups: [api-v1]
    message:
      groups: [api-v1]
    occurredOn:
#      serialized_name: occurred_on
      groups: [api-v1]
