LaSalle\GroupZero\Logging\Application\LogSummaryResponse:
  attributes:
    id:
      groups: [api-v1]
    environment:
      groups: [api-v1]
    level:
      groups: [api-v1]
    count:
      groups: [api-v1]
