LaSalle\GroupZero\Logging\Domain\Model\Aggregate\LogSummary:
  exclusion_policy: all
  accessor_order: custom
  custom_accessor_order: [ id, environment, level, count, updatedOn ]
  virtual_properties:
    count:
      name: count
      exp: object.count().toInt()
      type: integer
  properties:
    id:
      type: string
      expose: true
    environment:
      type: string
      expose: true
    level:
      type: string
      expose: true
    #    count:
    #      type: LaSalle\GroupZero\Logging\Domain\Model\ValueObject\LogCount
    #      expose: true
    updatedOn:
      type: DateTimeImmutable
      expose: true
