doctrine:
    orm:
        auto_generate_proxy_classes: false
#        metadata_cache_driver:
#            type: pool
#            pool: doctrine.filesystem
#        query_cache_driver:
#            type: pool
#            pool: doctrine.filesystem
#        result_cache_driver:
#            type: pool
#            pool: doctrine.filesystem


framework:
    cache:
        pools:
#            doctrine.filesystem:
#                adapter: cache.adapter.filesystem
