monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: stream
            path: "php://stderr"
            max_files: 15 # Because the default behavior is FILE_PER_DAY
            level: notice
            formatter: 'monolog.formatter.json'
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
#        deprecation:
#            type: stream
#            path: "php://stdout"
#        deprecation_filter:
#            type: filter
#            handler: deprecation
#            max_level: info
#            channels: ["php"]
