index:
    path: /hello
    controller: LaSalle\GroupZero\Logging\Infrastructure\Framework\Controller\HelloWorldController::helloWorld

#get_log_summaries:
#    path: /api/log-summaries
#    controller: LaSalle\GroupZero\Logging\Infrastructure\Framework\Controller\V1\GetCurrentEnvironmentLogSummariesController

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /hello
        permanent: true

sandbox_controllers:
    resource: './Logging/Infrastructure/Framework/Controller/Sandbox'
    prefix: /sandbox/
    name_prefix: sandbox_
    type:     annotation


v1_api_controllers:
    resource: './Logging/Infrastructure/Framework/Controller/V1'
    prefix: /api/{version}/
    condition:  "request.headers.get('Accept') matches '/application\\\\/json/i' or (request.getMethod() in ['PUT', 'POST', 'PATCH'] and request.headers.get('Content-Type') matches '/application\\\\/json/i')"
    name_prefix: logging_api_v1_
    type:     annotation
    defaults:
        _format: json
        version: v1

v2_api_controllers:
    type: rest
    resource: './Logging/Infrastructure/Framework/Controller/V2'
    prefix: /api/
    condition: "request.attributes.get('version') == '2.0'"
    name_prefix: logging_api_v2_

web_controllers:
    resource: './Logging/Infrastructure/Framework/Controller/Web'
    prefix: /
    name_prefix: logging_web_
    type:     annotation
    defaults:
        _format: html
