index:
    path: /hello
    controller: LaSalle\GroupZero\Logging\Infrastructure\Framework\Controller\HelloWorldController::helloWorld

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /hello
        permanent: true
