hello:
    path: /hello
    controller: LaSalle\GroupZero\Controller\HelloWorldController::helloWorld

hello_param_env:
    path: /hello-param-env
    controller: app.controller.hello_world_param_controller

