services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  _instanceof:
      LaSalle\GroupZero\Logging\Application\ApplicationService:
          tags: ['group_zero.application_service']


  # Extra with !tagged_iterator
  LaSalle\GroupZero\Logging\Infrastructure\Services\ApplicationServiceContainer:
    arguments:
      - !tagged_iterator group_zero.application_service

