parameters:
  app_log_summary_data_dir: '%env(resolve:APP_LOG_SUMMARY_DATA_DIR)%'

services:
  # default configuration for services in *this* file
  _defaults:
    public: false
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      string $kernelLogsDir: '%kernel.logs_dir%'
      string $kernelEnvironment: '%kernel.environment%'
      LaSalle\GroupZero\Logging\Domain\Model\Repository\LogEntryRepository: '@LaSalle\GroupZero\Logging\Infrastructure\Persistence\Filesystem\LogEntryFilesystemRepository'
      LaSalle\GroupZero\Logging\Domain\Model\Repository\LogSummaryRepository: '@LaSalle\GroupZero\Logging\Infrastructure\Persistence\Filesystem\FilesystemLogSummaryRepository'

  LaSalle\GroupZero\Logging\Domain\Model\Repository\LogEntryRepository:
    alias: 'LaSalle\GroupZero\Logging\Infrastructure\Persistence\Filesystem\LogEntryFilesystemRepository'

  LaSalle\GroupZero\Logging\Domain\Model\Repository\LogSummaryRepository:
    alias: 'LaSalle\GroupZero\Logging\Infrastructure\Persistence\Filesystem\FilesystemLogSummaryRepository'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  # Overrides all previously defined services under LaSalle\GroupZero\ namespace
  LaSalle\GroupZero\Logging\:
    resource: '%kernel.project_dir%/src/Logging/{Application,Domain,Infrastructure}/'
    exclude:
      - '%kernel.project_dir%/src/Logging/Infrastructure/Framework/{DependencyInjection}'
      - '%kernel.project_dir%/src/Logging/Domain/Model/{Aggregate,ValueObject,Exception}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  LaSalle\GroupZero\Logging\Infrastructure\Framework\Controller\:
    resource: '%kernel.project_dir%/src/Logging/Infrastructure/Framework/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  #    LaSalle\GroupZero\Logging\Infrastructure\Services\ApplicationServiceContainer:
  #        arguments:
  #            $services:
  #                - '@LaSalle\GroupZero\Logging\Application\GetLogEntriesByEnvironment'
  #                - '@LaSalle\GroupZero\Logging\Application\GetLogSummariesByEnvironment'

  #    LaSalle\GroupZero\Logging\Application\GetLogEntriesByEnvironment:
  #        tags:
  #            - { name: group_zero.application_service }
  #
  #    LaSalle\GroupZero\Logging\Application\GetLogSummariesByEnvironment:
  #        tags:
  #            - { name: group_zero.application_service }

  # Not needed because ApplicationService interface is autoconfigured kernel
  #    _instanceof:
  #        # services whose classes are instances of CustomInterface will be tagged automatically
  #        LaSalle\GroupZero\Logging\Application\ApplicationService:
  #            tags: ['group_zero.application_service']

  # Workaround just to have PSR-3 messages processed on our custom handler
  LaSalle\GroupZero\Logging\Infrastructure\Monolog\CreateLogEntryHandler:
    arguments:
      $kernelEnvironment: '%kernel.environment%'
    calls:
      - method: pushProcessor
        arguments:
          - '@monolog.processor.psr_log_message'

  LaSalle\GroupZero\Logging\Infrastructure\Persistence\Filesystem\FilesystemLogSummaryRepository:
    arguments:
      $directory: '%app_log_summary_data_dir%'

  #    LaSalle\GroupZero\Logging\Domain\Model\Event\Handler\IncreaseLogSummaryOnLogEntryCreated:
  #        autoconfigure: false
  #        tags:
  #            - {name: kernel.event_listener, event: LaSalle\GroupZero\Logging\Domain\Model\Event\LogEntryCreatedDomainEvent }
  #            - { name: messenger.message_handler, bus: event.bus }

  LaSalle\GroupZero\Logging\Domain\Model\Event\Handler\:
    resource: '%kernel.project_dir%/src/Logging/Domain/Model/Event/Handler/*.php'
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: event.bus }

  LaSalle\GroupZero\Core\Domain\Model\Event\DomainEventBus:
    alias: 'LaSalle\GroupZero\Core\Infrastructure\Event\MessengerDomainEventBus'
